### ISSUE TITLE
Send ButtonMessage in Group, reply privetly

### ISSUE THREAD

**Issue by tomlux** [Auties00/WhatsappWeb4j#157]
Hy,
I can send a ButtonMessage in a Group with your API 👍 an the members can also reply correctly on it as docuemented in the README

But when I'm configuring that only **admin** can write into the group, the members can no longer reply on my ButtonMessage (because they can't write into the group).

Is there a way to configure a Button to make the reply **privately**, so not answering into the group but only to the sender of the ButtonMessage.
Is this supported by WhatsApp? by your great Api?

**Comment by Auties00** [comment]
> Hy, I can send a ButtonMessage in a Group with your API 👍 an the members can also reply correctly on it as docuemented in the README
> 
> But when I'm configuring that only **admin** can write into the group, the members can no longer reply on my ButtonMessage (because they can't write into the group).
> 
> Is there a way to configure a Button to make the reply **privately**, so not answering into the group but only to the sender of the ButtonMessage. Is this supported by WhatsApp? by your great Api?

Honestly this is quite a nice question. 
I think that you can't mainly because those messages are intended to be used in business chats where you can always answer(a business chat cannot be a group). Maybe there's some way, but you'll have to explore it yourself as I have no idea. If it can be done, you can certainly do it using the api as it contains all the whatsapp classes.
